---
- name: Migrate Zabbix Agent 1 to Agent 2
  hosts: zabbix_agents
  become: true
  gather_facts: true
  serial: "{{ zabbix_agent2_migration_serial | default(10) }}"

  vars_files:
    - ../group_vars/zabbix_agents.yml

  roles:
    - role: zabbix_agent2_migration
